version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=production
      - APP_MODEL_NAME=${APP_MODEL_NAME}
      - MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI}
    restart: unless-stopped

#   mlflow:
#     build:
#       context: .
#       dockerfile: Dockerfile.mlflow
#     ports:
#       - "5001:5000"
#     volumes:
#       - ./mlruns:/mlruns     # Persist runs/artifacts on host
#     command: >
#       mlflow server
#       --host 0.0.0.0
#       --port 5000
#       --backend-store-uri file:/mlruns
#       --default-artifact-root file:/mlruns
#     restart: unless-stopped
#     networks:
#       - mlflow-net

# networks:
#   mlflow-net:
#     driver: bridge